apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template: #template for pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-c
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
  name: queue-release-1
  labels:
    app: queue
    release: "1"
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1

